columnSuffix: null
contentColumnType: string
fieldGroup: 9603d0d8-6306-462f-a967-b1719be59cd2 # meubels
handle: meubelImage
instructions: 'plaats een nieuwe afbeelding'
name: 'meubel Image'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
    - video
  branchLimit: null
  defaultUploadLocationSource: 'volume:538cba14-d0f8-4365-9d15-694d4b417ee0' # meubels
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:538cba14-d0f8-4365-9d15-694d4b417ee0' # meubels
  restrictedLocationSubpath: null
  selectionLabel: 'meubel foto toevoegen'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
