fieldLayouts:
  1921cb29-dd5a-40dd-b559-dbe7be225021:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 264ce268-e5eb-489e-b0aa-d1238c69da92
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4bd720e4-7517-4017-b274-fec9a28bbbd0
        userCondition: null
handle: header
hasTitleField: true
name: header
section: 73eeabaf-f915-409a-9a3b-691c8e1c24a5 # header
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
