fieldLayouts:
  a5451bb8-01ea-47ca-ae22-0b1d182720d8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: cc200480-e5ff-46b1-b444-92d3798e09c8 # beschrijving
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed9e1877-ada4-4d87-b117-9d7c2b709109
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 03727efa-ff38-40c7-806c-c335632b6f1e # meubel Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 59617603-8d80-4e10-9ea2-496c56e11e21
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 67acd255-39ff-46f6-829e-e16dfd806e3a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ae7581b7-0a02-409f-aeab-de5ba0d6eb81 # categorien
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c2937e98-ad1d-4586-b3ba-bbf68b1bab9c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 14004384-f7d8-482a-a0fd-00d8c56b5c8f # prijs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 63530d6e-7a46-430f-88a9-fa3531ba29e6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 78748bfb-90fe-4e65-bca2-fe4538d6ad3c
        userCondition: null
handle: meubels
hasTitleField: true
name: meubels
section: 7191d1fe-0469-4222-8421-739013ce3494 # meubels
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
