defaultPlacement: end
enableVersioning: true
handle: meubels
name: meubels
propagationMethod: all
siteSettings:
  75d00fd6-59d1-4155-8a76-00491194e8ff: # examen-Jonas-van-roy
    enabledByDefault: true
    hasUrls: true
    template: drinks/_entry
    uriFormat: 'drinks/{slug}'
type: channel
