fieldLayouts:
  b98d6397-56db-4190-8264-c3433ab0bbf1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 47b69dff-2552-48d1-b7c9-cbbc19bf087c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9f8455d6-db97-4efc-8d4d-26b9484ddb4a
        userCondition: null
fs: images
handle: meubels
name: meubels
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
